name: Build, Push, and Mark

on:
  pull_request:
    types: [closed]

jobs:
  build-push-mark:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Build, push Docker image, and mark version
        run: ./build-and-push.sh --build-push-mark
        env:
          BASE_URL: https://release.memsql.com/production/debian/pool/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo "Branch name determined as: main"
          echo "Committing and pushing changes to branch: main"
          git add .built_versions
          git diff-index --quiet HEAD || git commit -m "Update .built_versions"
          git push https://${{ secrets.PAT }}@github.com/nithinM/singlestore-studio.git HEAD:refs/heads/main
