name: Build, Push, and Mark on Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  build-push-mark:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure we get all history for .built_versions tracking

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, push Docker image, and mark version
        run: ./build-and-push.sh --build-push-mark
        env:
          BASE_URL: https://release.memsql.com/production/debian/pool/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Commit version.txt changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add version.txt .built_versions
          git commit -m "Mark version as built" -a || echo "No changes to commit"
          git push
