name: Build, Push, and Mark

on:
  pull_request_review:
    types: [submitted]

jobs:
  build-push-mark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure we get all history for .built_versions tracking

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, push Docker image, and mark version
        run: ./build-and-push.sh --build-push-mark
        env:
          BASE_URL: https://release.memsql.com/production/debian/pool/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Commit versions.txt changes
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "commit message" || echo "No changes to commit"
          git remote set-url origin https://nithinM:${PAT_TOKEN}@github.com/yourusername/yourrepo.git
          git push origin HEAD:refs/heads/${{ github.head_ref }}
