name: Build, Push, and Mark

on:
  pull_request_review:
    types: [submitted]

jobs:
  build-push-mark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure we get all history for .built_versions tracking
          ref: ${{ github.head_ref }} # Checkout the head ref branch, useful for pull_request_target event

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, push Docker image, and mark version
        run: ./build-and-push.sh --build-push-mark
        env:
          BASE_URL: https://release.memsql.com/production/debian/pool/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Commit version.txt changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # Use the PAT for pushing
          git push https://${{ secrets.PAT }}@github.com/nithinM/singlestore-studio.git HEAD:refs/heads/$BRANCH
