name: PR Build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image from PR
        run: ./build-and-push.sh --build-only
        env:
          BASE_URL: https://release.memsql.com/production/debian/pool/
