name: PR Build and Auto-Assign

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  build-and-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # This fetches the PR code safely by referencing the PR's HEAD commit SHA.
          # Important: Ensure any subsequent steps that execute code are secure.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image from PR
        run: ./build-and-push.sh --build-only
        env:
          BASE_URL: https://release.memsql.com/production/debian/pool/

      - name: Auto-assign PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: ['nithinM']
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
